[package]
name = "boa_idb_fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.boa_idb_core]
path = "../crates/boa_idb_core"

[[bin]]
name = "fuzz_key_decode"
path = "fuzz_targets/fuzz_key_decode.rs"

[[bin]]
name = "fuzz_scf_decode"
path = "fuzz_targets/fuzz_scf_decode.rs"

[[bin]]
name = "fuzz_keypath_parse"
path = "fuzz_targets/fuzz_keypath_parse.rs"
